name: jads-nhs-proms
channels:
- defaults
dependencies:
- dephell ==0.*,>=0.8.3
- ipykernel ==5.*,>=5.3.4
- matplotlib ==3.*,>=3.3.0
- numpy ==1.*,>=1.19.1
- pandas ==1.*,>=1.0.0
- pyarrow ==1.*,>=1.0.0
- seaborn ==0.*,>=0.10.1
- yellowbrick ==1.*,>=1.1.0
- black ==19.*,>=19.10.0.b0
- imbalanced-learn ==0.*,>=0.7.0
- toolz ==0.*,>=0.10.0
- jupyter ==1.*,>=1.0.0
